# Generated by Django 5.1 on 2024-10-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try_on', '0002_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='typesOfClothes',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='types_of_clothes',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Workwear', 'Workwear'), ('Social Occasions', 'Social Occasions'), ('Maternity', 'Maternity')], default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.IntegerField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sleeves',
            field=models.CharField(choices=[('Too short', 'Too short'), ('Just right', 'Just right'), ('Too long', 'Too long')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='weight',
            field=models.IntegerField(blank=True, default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Jacket', 'Jacket'), ('Dress', 'Dress'), ('Pants', 'Pants'), ('Skirt', 'Skirt'), ('Shoes', 'Shoes'), ('Bag', 'Bag'), ('Accessory', 'Accessory')], max_length=50),
        ),
    ]
